apiVersion: v1
kind: Namespace
metadata:
  name: s32s3
---
apiVersion: v1
kind: Secret
metadata:
  name: s32s3-config
  namespace: s32s3
type: Opaque
stringData:
  rclone.conf: |
    [source]
    type = s3
    provider = Minio
    access_key_id = rclone-user
    secret_access_key = 1oI6wpWgMFWdRaYbuZf6CsyrtM2HOnL7CeQAJCh4
    endpoint = http://bitnami-minio.minio:9000
    acl = private
    bucket_acl = private

    [dest]
    type = crypt
    remote = backup:
    directory_name_encryption = false
    password = EjCf9fA-O0ZruaA-bebUDeSlE88jKL3xTZulwAKU-nWtCfQi0q4I25GeYttKAFybk9e9oqF1JkouZQ9zaJoHusPKIg4qGLx7uQyj3L18xNW_MpPCgqOtgAPkKs23OwcIKISdcTbM

    [backup]
    type = s3
    provider = Minio
    access_key_id = rclone-user
    secret_access_key = NL671NA8VyWT4eBdqKGUQlH1xTLmRloNGZ2HlIGB
    endpoint = http://bitnami-minio.backup:9000
    acl = private
    bucket_acl = private
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s32s3
  namespace: s32s3
  labels:
    app: s32s3
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: s32s3
        spec:
          restartPolicy: Never
          containers:
          - image: ctr.0x.pt/ops/s32s3:latest
            name: s32s3
            args:
            - backup
            env:
            - name: RCLONE_BUCKET_PREFIX
              value: backup-
            resources:
              limits:
                cpu: "200m"
                memory: "500M"
            volumeMounts:
            - mountPath: /etc/rclone.conf
              name: config
              subPath: rclone.conf
          volumes:
          - name: config
            secret:
              secretName: s32s3-config
