apiVersion: batch/v1
kind: Job
metadata:
  name: s32s3-restore
  namespace: s32s3
spec:
  template:
    metadata:
      name: s32s3-restore
    spec:
      restartPolicy: Never
      containers:
      - image: ctr.0x.pt/ops/s32s3:latest
        imagePullPolicy: IfNotPresent
        name: s32s3
        args:
        - restore
        env:
        - name: RCLONE_BUCKET_PREFIX
          value: backup-
        resources:
          limits:
            cpu: "200m"
            memory: "500M"
        volumeMounts:
        - mountPath: /etc/rclone.conf
          name: config
          subPath: rclone.conf
      volumes:
      - name: config
        secret:
          secretName: s32s3-config
