repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # admin creds:
  # {{/* kubectl get secrets bitnami-minio -otemplate='{{range $key, $value := .data}}{{$key}}: {{ $value | base64decode }}{{"\n"}}{{end}}' -n backup */}}
  - name: bitnami
    chart: bitnami/minio
    namespace: minio
    values:
      - auth:
          rootPassword: "NL671NA8VyWT4eBdqKGUQ2H1xTLmRloNGZ2HlIGB"
  - name: bitnami
    chart: bitnami/minio
    namespace: backup
    values:
      - auth:
          rootPassword: "NL671NA8VyWT4eBdqKGUQlH1xTLmRloNGZ2HlIGB"
  - name: s32s3
    chart: ../chart
    force: true
    namespace: minio
    values:
      - image:
          tag: latest
          pullPolicy: Never
        config:
          source:
            access_key_id:
              valueFrom:
                secretKeyRef:
                  name: bitnami-minio
                  key: root-user
            secret_access_key:
              valueFrom:
                secretKeyRef:
                  name: bitnami-minio
                  key: root-password
            endpoint:
              value: "http://bitnami-minio:9000"
          destination:
            access_key_id:
              value: "rclone-user"
            secret_access_key:
              value: "NL671NA8VyWT4eBdqKGUQlH1xTLmRloNGZ2HlIGB"
            endpoint:
              value: "http://bitnami-minio.backup:9000"
            region:
              value: "us-east-1"
          crypt:
            password:
              value: "password"
            password2:
              value: "salt"
          rclone:
            max_backlog:
              value: "1000"
        # restore:
        #   enabled: true
        #   at: "10h"
