kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: "rclone-s3-backup"
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
  - role: worker
    image: kindest/node:v1.31.0
