apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Release.Name }}-backup
  namespace: {{.Release.Namespace }}
  labels: {{ include "s32s3.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.config.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      podFailurePolicy:
        rules:
          - action: FailJob
            onExitCodes:
              containerName: {{.Release.Name }}-backup
              values: [0]
              operator: NotIn
      template:
        spec:
          imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 12 }}
          serviceAccountName: {{.Release.Name }}
          securityContext: {{ toYaml .Values.podSecurityContext | nindent 12 }}
          nodeSelector: {{ toYaml .Values.nodeSelector | nindent 12 }}
          tolerations: {{ toYaml .Values.tolerations | nindent 12 }}
          affinity: {{ toYaml .Values.affinity | nindent 12 }}
          restartPolicy: Never
          containers:
            - name: {{.Release.Name }}-backup
              image: "{{ .Values.image.repository }}{{if .Values.image.tag}}:{{.Values.image.tag }}{{end}}"
              resources: {{ toYaml .Values.resources | nindent 16 }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - backup
              env:
                - name: BUCKET_PREFIX
                  value: {{ .Values.config.bucketPrefix | quote }}
                - name: CRYPT_PASSWORD
                  {{- if .Values.config.crypt.password }}
                  {{- .Values.config.crypt.password | toYaml | nindent 18}}
                  {{- else }}
                  {{ fail (printf "config.crypt.password is required") }}
                  {{- end }}
                - name: CRYPT_PASSWORD2
                  {{- if .Values.config.crypt.password2 }}
                  {{- .Values.config.crypt.password2 | toYaml | nindent 18}}
                  {{- else }}
                  {{ fail (printf "config.crypt.password2 is required") }}
                  {{- end }}
                  {{- range $key, $value :=.Values.config.destination }}
                - name: DEST_{{ $key | upper }}
                  {{- $value | toYaml | nindent 18}}
                  {{- end }}
                  {{- range $key, $value :=.Values.config.source }}
                - name: SOURCE_{{ $key | upper }}
                  {{- $value | toYaml | nindent 18}}
                  {{- end }}