{{- if not .Values.restore.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Release.Name }}-backup
  namespace: {{.Release.Namespace }}
  labels: {{ include "s32s3.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.config.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      podFailurePolicy:
        rules:
          - action: FailJob
            onExitCodes:
              containerName: {{.Release.Name }}-backup
              values: [0]
              operator: NotIn
      template:
        spec:
          imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 12 }}
          securityContext: {{ toYaml .Values.podSecurityContext | nindent 12 }}
          nodeSelector: {{ toYaml .Values.nodeSelector | nindent 12 }}
          tolerations: {{ toYaml .Values.tolerations | nindent 12 }}
          affinity: {{ toYaml .Values.affinity | nindent 12 }}
          restartPolicy: Never
          containers:
            - name: {{.Release.Name }}-backup
              image: "{{ .Values.image.repository }}{{if .Values.image.tag}}:{{.Values.image.tag }}{{end}}"
              resources: {{ toYaml .Values.resources | nindent 16 }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - backup
              env:
                  {{- range $key, $value := .Values.config.crypt -}}
                  {{- include "s32s3.envVar" (list (printf "Values.config.crypt.%s" $key) (printf "CRYPT_%s" ($key | upper)) $value) | nindent 16 }}
                  {{- end }}
                  {{- range $key, $value := .Values.config.destination }}
                  {{- include "s32s3.envVar" (list (printf "Values.config.destination.%s" $key) (printf "DEST_%s" ($key | upper)) $value) | nindent 16 }}
                  {{- end }}
                  {{- range $key, $value := .Values.config.source }}
                  {{- include "s32s3.envVar" (list (printf "Values.config.source.%s" $key) (printf "SOURCE_%s" ($key | upper)) $value) | nindent 16 }}
                  {{- end }}
                - name: BACKUP_BUCKET
                  value: {{ .Values.config.backupBucket | quote }}
                  {{- range $key, $value := .Values.config.extraEnv}}
                - name: EXPIRATION_DAYS
                  value: {{ .Values.config.expirationDays | quote }}
                - name: {{ $key | quote }}
                  value: {{ $value | quote }}
                  {{- end }}
{{- end}}