{{- if .Values.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name }}-restore
  namespace: {{.Release.Namespace }}
  labels: {{ include "s32s3.labels" . | nindent 4 }}
spec:
  template:
    spec:
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 12 }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 12 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 12 }}
      affinity: {{ toYaml .Values.affinity | nindent 12 }}
      restartPolicy: Never
      containers:
        - name: {{.Release.Name }}-restore
          image: "{{ .Values.image.repository }}{{if .Values.image.tag}}:{{.Values.image.tag }}{{end}}"
          resources: {{ toYaml .Values.resources | nindent 16 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - restore
          env:
            {{- include "s32s3.envVar" (list "Values.config.crypt.password" "CRYPT_PASSWORD" .Values.config.crypt.password) | nindent 10 }}
            {{- include "s32s3.envVar" (list "Values.config.crypt.password" "CRYPT_PASSWORD2" .Values.config.crypt.password2) | nindent 10 }}
            {{- range $key, $value :=.Values.config.destination }}
            {{- include "s32s3.envVar" (list (printf "Values.config.destination.%s" $key) (printf "DEST_%s" ($key | upper)) $value) | nindent 10 }}
            {{- end }}
            {{- range $key, $value :=.Values.config.source }}
            {{- include "s32s3.envVar" (list (printf "Values.config.source.%s" $key) (printf "SOURCE_%s" ($key | upper)) $value) | nindent 10 }}
            {{- end }}
          - name: BACKUP_BUCKET
            value: {{ .Values.config.backupBucket | quote }}
            {{- range $key, $value := .Values.config.extraEnv}}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
            {{- end }}
{{- end }}