name: Build Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-containers:
    env:
      IMAGE: "ctr.0x.pt/ops/s32s3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ctr.0x.pt
          username: robot$s32s3
          password: ${{ secrets.CTR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{env.IMAGE}}:latest
            ${{ github.ref_type == 'tag' && format('{0}:{1}', env.IMAGE, github.ref_name) || '' }}
