name: Build Image

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ctr.0x.pt
        username: robot$s32s3
        password: ${{ secrets.CTR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./image
        push: true
        tags: ctr.0x.pt/ops/s32s3:latest
